###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: laravel-excel-mysql
      working_dir: /application
      volumes:
       - ./infra/mysql:/var/lib/mysql
      environment:
              - MYSQL_ROOT_PASSWORD=root
              - MYSQL_DATABASE=db_laravel_excel
              - MYSQL_USER=root
              - MYSQL_PASSWORD=root
      ports:
       - "33060:3306"

    webserver:
      image: nginx:alpine
      container_name: laravel-excel-webserver
      working_dir: /application
      volumes:
          - ./src:/application
          - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9000:80"

    php-fpm:
      build: infra/php-fpm
      container_name: laravel-excel-php-fpm
      working_dir: /application
      volumes:
        - ./src:/application
        - ./infra/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
